spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    url: jdbc:h2:~/accountbook;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #logger를 통해 로그 출력
  h2:
    console:
      enabled: true
      path: /h2-console
logging :
  root: info
  level:
    org:
      hibernate:
        type : INFO
      springframework:
        security: INFO

